ChainID = '60808'
# OP stack https://docs.gobob.xyz/learn/introduction/stack-overview#rollup-layer
ChainType = 'optimismBedrock'
# finality_depth was: ~850
FinalityDepth = 900
# block_time was:  2s
LogPollInterval = '5s'

# finality_depth * block_time / 60 secs = ~30  min (finality time)
NoNewFinalizedHeadsThreshold = '35m'

FinalityTagEnabled = true

[GasEstimator]
EIP1559DynamicFees = true
Mode = 'FeeHistory'

[GasEstimator.FeeHistory]
# block_time was: 2s
CacheTimeout = '2s'

[GasEstimator.BlockHistory]
BlockHistorySize = 100
