ChainID = '1301'
# OP stack: https://docs.unichain.org/docs/getting-started/set-up-a-node#overview
ChainType = 'optimismBedrock'
# finality_depth was: ~1900
FinalityDepth = 2000
# block_time was:  ~1s 
LogPollInterval = '5s'

# batching_size_finalization_percentage = 30% according to the explorer batching view
# ( batching_size_finalization_percentage * finality_depth) * block_time / 60 secs = ~33  min (finality time)
NoNewFinalizedHeadsThreshold = '10m'

FinalityTagEnabled = true

[GasEstimator]
EIP1559DynamicFees = true
Mode = 'FeeHistory'

[GasEstimator.FeeHistory]
# block_time was: 1s
CacheTimeout = '1s'

[GasEstimator.BlockHistory]
BlockHistorySize = 100
